### ISSUE TITLE
Add project of  practice proactive

### ISSUE THREAD

**Issue by electron0zero** [RiflerRick/StockholmHotline#2]
i think this project can be used as a great learning assignment for people who are learning socket programming.
we would love to have it as a ongoing project in practice proactive.
here is [list of project](https://github.com/practice-proactive/HelloWorld/blob/master/projects.md)
here is [steps to add a project](https://github.com/practice-proactive/HelloWorld/blob/master/projects.md#steps-to-propose-a-project-new-package)

**Comment by RiflerRick** [comment]
done!!!
